# Configuration par défaut pour les différents jeux
game.tictactoe.default-player-count=2
game.tictactoe.default-board-size=3

game.taquin.default-player-count=1
game.taquin.default-board-size=4

game.connectfour.default-player-count=2
game.connectfour.default-board-size=7

spring.profiles.active=h2

jwt.secret=change-moi-cette-cle-secrete-pour-une-cle-longue-et-aleatoire-123456789