# Configuration par défaut pour les différents jeux
game.tictactoe.default-player-count=2
game.tictactoe.default-board-size=3

game.taquin.default-player-count=1
game.taquin.default-board-size=4

game.connectfour.default-player-count=2
game.connectfour.default-board-size=7

spring.datasource.url=jdbc:postgresql://localhost:5432/square_games
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update